package com.j4ml.dao.mapper;

import com.j4ml.dao.bean.SysUser;

public interface SysUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user
     *
     * @mbggenerated Tue Jun 14 18:03:09 CST 2016
     */
    int deleteByPrimaryKey(String sysUserId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user
     *
     * @mbggenerated Tue Jun 14 18:03:09 CST 2016
     */
    int insert(SysUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user
     *
     * @mbggenerated Tue Jun 14 18:03:09 CST 2016
     */
    int insertSelective(SysUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user
     *
     * @mbggenerated Tue Jun 14 18:03:09 CST 2016
     */
    SysUser selectByPrimaryKey(String sysUserId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user
     *
     * @mbggenerated Tue Jun 14 18:03:09 CST 2016
     */
    int updateByPrimaryKeySelective(SysUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user
     *
     * @mbggenerated Tue Jun 14 18:03:09 CST 2016
     */
    int updateByPrimaryKey(SysUser record);
}