package com.j4ml.dao.bean;

import java.util.Date;

public class SysUser{
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.sys_user_id
     *
     * @mbggenerated Tue Jun 14 18:03:09 CST 2016
     */
    private String sysUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.sys_user_name
     *
     * @mbggenerated Tue Jun 14 18:03:09 CST 2016
     */
    private String sysUserName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.sys_user_pwd
     *
     * @mbggenerated Tue Jun 14 18:03:09 CST 2016
     */
    private String sysUserPwd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.create_time
     *
     * @mbggenerated Tue Jun 14 18:03:09 CST 2016
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.status
     *
     * @mbggenerated Tue Jun 14 18:03:09 CST 2016
     */
    private String status;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.sys_user_id
     *
     * @return the value of sys_user.sys_user_id
     *
     * @mbggenerated Tue Jun 14 18:03:09 CST 2016
     */
    public String getSysUserId() {
        return sysUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.sys_user_id
     *
     * @param sysUserId the value for sys_user.sys_user_id
     *
     * @mbggenerated Tue Jun 14 18:03:09 CST 2016
     */
    public void setSysUserId(String sysUserId) {
        this.sysUserId = sysUserId == null ? null : sysUserId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.sys_user_name
     *
     * @return the value of sys_user.sys_user_name
     *
     * @mbggenerated Tue Jun 14 18:03:09 CST 2016
     */
    public String getSysUserName() {
        return sysUserName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.sys_user_name
     *
     * @param sysUserName the value for sys_user.sys_user_name
     *
     * @mbggenerated Tue Jun 14 18:03:09 CST 2016
     */
    public void setSysUserName(String sysUserName) {
        this.sysUserName = sysUserName == null ? null : sysUserName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.sys_user_pwd
     *
     * @return the value of sys_user.sys_user_pwd
     *
     * @mbggenerated Tue Jun 14 18:03:09 CST 2016
     */
    public String getSysUserPwd() {
        return sysUserPwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.sys_user_pwd
     *
     * @param sysUserPwd the value for sys_user.sys_user_pwd
     *
     * @mbggenerated Tue Jun 14 18:03:09 CST 2016
     */
    public void setSysUserPwd(String sysUserPwd) {
        this.sysUserPwd = sysUserPwd == null ? null : sysUserPwd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.create_time
     *
     * @return the value of sys_user.create_time
     *
     * @mbggenerated Tue Jun 14 18:03:09 CST 2016
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.create_time
     *
     * @param createTime the value for sys_user.create_time
     *
     * @mbggenerated Tue Jun 14 18:03:09 CST 2016
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.status
     *
     * @return the value of sys_user.status
     *
     * @mbggenerated Tue Jun 14 18:03:09 CST 2016
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.status
     *
     * @param status the value for sys_user.status
     *
     * @mbggenerated Tue Jun 14 18:03:09 CST 2016
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }
}